services:
  - type: web
    name: nekop-ai
    runtime: python
    rootDir: PRODIGY_ML_03
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
